---

- name: Create backup config directory
  file:
    path:  "{{ item }}"
    owner: "{{ backup_setup.user }}"
    group: "{{ backup_setup.user }}"
    state: directory
  with_items:
    - "{{ backup_setup.config_dir }}"
    - "{{ backup_setup.config_dir }}/models"
    - "{{ backup_setup.tmp_dir }}"
    - "{{ backup_setup.data_dir }}"
    - "{{ backup_setup.log_dir }}"
    - "{{ backup_setup.local_store }}"

- name: Copy custom backup
  sudo: yes
  copy: 
    src: cli_s3_syncer.rb
    dest: "{{ backup_setup.config_dir }}"
    owner: "{{ backup_setup.user }}"
    group: "{{ backup_setup.user }}"

- name: Configure backups config
  template:
    src:   config.rb.j2
    dest:  "{{ backup_setup.config_dir }}/config.rb"
    owner: "{{ backup_setup.user }}"
    group: "{{ backup_setup.user }}"
    mode:  0600

- name: Configure backups models
  template:
    src:   model.rb.j2
    dest:  "{{ backup_setup.config_dir }}/models/{{ item.key }}.rb"
    owner: "{{ backup_setup.user }}"
    group: "{{ backup_setup.user }}"
    mode:  0600
  with_dict: "{{ backup_jobs }}"

- name: Configure cron
  template:
    src:   cron.j2
    dest:  "/etc/cron.d/backup"
    owner: "{{ backup_setup.user }}"
    group: "{{ backup_setup.user }}"
    mode:  0700
