---
- name: Setup BrightBox PPA for ruby packages
  apt_repository:
    repo: "ppa:brightbox/ruby-ng"

- name: ruby | Install
  apt:
    pkg:              "{{ item }}"
    state:            installed
    update_cache:     yes
    cache_valid_time: 3600
  with_items:
    - "{{ backup_ruby_package }}"
    - "{{ backup_ruby_dev_package }}"
  tags: [ backup_ruby ]

- name: build utils | install
  apt:
    pkg:              "{{ item }}"
    state:            installed
    update_cache:     yes
    cache_valid_time: 3600
  with_items:
    - autoconf
    - binutils-doc
    - bison
    - build-essential
    - flex
    - gettext
    - ncurses-dev
    - python-pip
    - zlib1g-dev

- name: Install gem backup
  gem:
    name:         backup
    state:        present
    user_install: false

- name: awscli | install
  pip:
    name: awscli
